name: tally_counter
description: A professional tally counter mobile app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      # fonts:
      #   - asset: assets/fonts/Inter-Regular.ttf
      #   - asset: assets/fonts/Inter-Bold.ttf
      #     weight: 700
